apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: devops-exercise
type: Opaque
data:
  # Base64 encoded "admin"
  admin-user: YWRtaW4=
  # Base64 encoded "mysecurepassword"
  admin-password: bXlzZWN1cmVwYXNzd29yZA==
